auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “ZJZ's Blog”
title: ZJZ's blog
description: Everything about ZJZ.
url: http://zhengjinzhong.github.io
feed: /atom.xml
author_info: <a href="http://zhengjinzhong.github.io/">ZJZ</a>
